name: office_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  pinput: ^5.0.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.7.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/core/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Bahij TheSansArabic
      fonts:
        - asset: assets/fonts/Bahij TheSansArabic/Bahij_TheSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/Bahij TheSansArabic/Bahij_TheSansArabic-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Bahij TheSansArabic/Bahij_TheSansArabic-Bold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
